---
# tasks file for getsessions
- name: Get sessions
  ilo_redfish_config:
    category: Sessions
    command: GetiLOSessions
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr
