---
# tasks file for getvirtmediainfo
- name: Get Virtual Media information
  redfish_info:
    category: Manager
    command: GetVirtualMedia
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr
