---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Get network boot settings
      get_boot_settings:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: network_boot_settings

    - name: Boot settings present in the server
      debug:
        msg: "{{ network_boot_settings }}"
