---
# tasks file for ledon
- name: Turn LED on
  redfish_command:
    category: Chassis
    command: IndicatorLedOn
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
