---
# tasks file for configHostName
- name: Set Manager NIC
  redfish_config:
    category: Manager
    command: SetManagerNic
    nic_config:
      HostName: "{{ attribute_value }}"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
