---
# tasks file for ledoff
- name: Turn LED off
  redfish_command:
    category: Chassis
    command: IndicatorLedOff
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
