---
- hosts: myhosts
  connection: local
  name: List Users
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    datatype: UserList

  tasks:
    - name: Create session
      redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Set output file
      include_tasks: create_output_file.yml

    - name: List all users
      redfish_info:
        category: Accounts
        command: ListUsers
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: result_users

    - name: Copy results to output file
      copy:
        content: "{{ result_users | to_nice_json }}"
        dest: "{{ template }}.json"

    - name: Delete session using security token created by CreateSesssion above
      redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
